---
title: "Research"
description: "A collection of Yanghao Wang's academic research and refereed publications in applied economics, industrial organization, and public policy."
body-classes: hide-title-block
---

## Refereed Publications

<ol>
    <li>
        <p style="text-align: justify;"><strong>Wang, Yanghao</strong>, Metin Çakır, and Timothy A. Park. 2025. "<a href="https://onlinelibrary.wiley.com/share/author/4RV9PZN77GGARYHBSJ9X?target=10.1111/ajae.12461" target="_blank">The Role of Geographic Market Definition in Analysis of Grocery Retailing.</a>" <em>American Journal of Agricultural Economics</em> 107(1): 208-230.
        </p>
    </li>
    <li>
        <p style="text-align: justify;">Çakır, Metin, Timothy K. M. Beatty, Michael A. Boland, Qingxiao Li, Timothy A. Park, and <strong>Yanghao Wang</strong>. 2022. "<a href="https://onlinelibrary.wiley.com/doi/epdf/10.1002/jaa2.7" target="_blank">An Index Number Approach to Estimating Organic Price Premia at Retail.</a>" <em>Journal of the Agricultural and Applied Economics Association</em> 1(1): 33-46.
        </p>
    </li>
    <li>
        <p style="text-align: justify;"><strong>Wang, Yanghao</strong>, Wei Shi, and Zhenhua Chen. 2021. "<a href="https://doi.org/10.1016/j.trd.2021.103085" target="_blank">Impact of Ride-hailing Usage on Vehicle Ownership in the United States.</a>" <em>Transportation Research Part D: Transport and Environment</em> 101: 103085.
        </p>
    </li>
    <li>
        <p style="text-align: justify;">Zhang, Jun, <strong>Yanghao Wang</strong>, and Steven T. Yen. 2021. "<a href="https://doi.org/10.3390/ijerph18063178" target="_blank">Does Supplemental Nutrition Assistance Program Reduce Food Insecurity among Households with Children? Evidence from the Current Population Survey.</a>" <em>International Journal of Environmental Research and Public Health</em>  18(6): 3178.
        </p>
    </li>
    <li>
        <p style="text-align: justify;"><strong>Wang, Yanghao</strong> and Metin Çakır. 2021. "<a href="https://onlinelibrary.wiley.com/share/author/YMZYTRFP8ANBQXFAEG6X?target=10.1111/agec.12614" target="_blank">Welfare Impacts of Increasing Teff Prices on Ethiopian Consumers.</a>" <em>Agricultural Economics</em>  52(2): 195-213.
        </p>
    </li>
    <li>
        <p style="text-align: justify;"><strong>Wang, Yanghao</strong> and Metin Çakır. 2020. "<a href="https://onlinelibrary.wiley.com/share/author/IEMJCATYHSZBYI5CAMAR?target=10.1111/agec.12564" target="_blank">Welfare Impacts of New Demand-Enhancing Agricultural Products: The Case of Honeycrisp Apples.</a>" <em>Agricultural Economics</em> 51(3): 445-457.
        </p>
    </li>
    <li>
        <p style="text-align: justify;">Çakır, Metin, Timothy K.M. Beatty, Michael A. Boland, Timothy A. Park, Samantha Snyder, and <strong>Yanghao Wang</strong>. 2018. "<a href="https://doi.org/10.1093/ajae/aay002" target="_blank">Spatial and Temporal Variation in the Value of the WIC Programs Fruit and Vegetable Voucher.</a>" <em>American Journal of Agricultural Economics</em> 100(3): 691-706.
        </p>
    </li>
    <li>
        <p style="text-align: justify;">Çakır, Metin, Michael A. Boland, and <strong>Yanghao Wang</strong>. 2018. "<a href="https://doi.org/10.1093/aepp/ppx027" target="_blank">The Economic Impacts of 2015 Avian Influenza Outbreak on the U.S. Turkey Industry and the Loss Mitigating Role of Free Trade Agreements.</a>" <em>Applied Economic Perspectives and Policy</em> 40(2): 297-315.
        </p>
    </li>
    <li>
        <p style="text-align: justify;">Tan, Andrew K.G., <strong>Yanghao Wang</strong>, Steven T. Yen, and Mustapha I. Feisul. 2016. "<a href="https://doi.org/10.1093/aepp/ppv020" target="_blank">Physical Activity and Body Weight among Adults in Malaysia.</a>" <em>Applied Economic Perspectives and Policy</em> 38 (2): 318-33.
        </p>
    </li>
</ol>
